/* Generated by: CongoCC Parser Generator. InvalidToken.java  */
package net.magneticpotato.sqlexpr.congocc.parser;


/**
* Token subclass to represent lexically invalid input
*/
public class InvalidToken extends Token {

    public InvalidToken(SqlExprParserLexer tokenSource, int beginOffset, int endOffset) {
        super(TokenType.INVALID, tokenSource, beginOffset, endOffset);
    }

}


