/* Generated by: CongoCC Parser Generator. Do not edit.
* Generated Code for comparisonExpression AST Node type
* by the ASTNode.java.ftl template
*/
package net.magneticpotato.sqlexpr.congocc.parser.ast;

import net.magneticpotato.sqlexpr.congocc.parser.*;
import java.util.*;
import static net.magneticpotato.sqlexpr.congocc.parser.Token.TokenType.*;


public class comparisonExpression extends BaseNode {
}


