/* Generated by: CongoCC Parser Generator. Do not edit.
* Generated Code for FLOATING_POINT_LITERAL Token subclass
* by the ASTToken.java.ftl template
*/
package net.magneticpotato.sqlexpr.congocc.parser.ast;

import net.magneticpotato.sqlexpr.congocc.parser.*;
import static net.magneticpotato.sqlexpr.congocc.parser.Token.TokenType.*;


public class FLOATING_POINT_LITERAL extends Token {

    public FLOATING_POINT_LITERAL(TokenType type, SqlExprParserLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}


