/* Generated by: CongoCC Parser Generator. Do not edit.
* Generated Code for IS Token subclass
* by the ASTToken.java.ftl template
*/
package net.magneticpotato.sqlexpr.congocc.parser.ast;

import net.magneticpotato.sqlexpr.congocc.parser.*;
import static net.magneticpotato.sqlexpr.congocc.parser.Token.TokenType.*;


public class IS extends Token {

    public IS(TokenType type, SqlExprParserLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}


